# Generated by Django 4.1 on 2022-08-22 13:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=10)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('reg_date', models.DateField(default=datetime.date.today, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive')], default=2, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile Info',
                'verbose_name_plural': 'User Profile Info',
                'db_table': 'tb_register',
            },
        ),
    ]
